name = "waffle's Modpack"
author = "triphora"
version = "2023.04.21"
description = "Highly customizable rolling-release client-side pack compatible with any multiplayer server, focusing on performance and features that still feel true to vanilla."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cf24a80a6ab861b050648f23efc9228b2d7c006679bc0526477475b08b35117"

[versions]
minecraft = "1.19.4"
quilt = "0.18.5"
